### PR TITLE
PR for issue #90 - "How do I set a token lifetime to infinity?"

### PR DESCRIPTION
**Pull request by pedrofurtado**
@djoos , 

PR for issue #90 .

It allows that developer can override the way of token is expired. By default, the bundle already provides a ready solution.

It will be apreciated a review, because I don't know very well the structure of code of the bundle. Thanks!

### CODE REVIEW

**Comment by djoos** [comment]
Thank you @pedrofurtado - looks good to me!

Nitpicking mode: would you mind changing `lifetime: 300 (or -1 for no-expirable tokens)` to `lifetime: 300 # or -1 for infinite lifetime tokens (please use with extreme care!)`

If you could make that small change and squash the commits into 1, I'm happy to get this merged and shipped ASAP.

Thanks in advance!
David

**Comment by pedrofurtado** [comment]
@djoos Thanks for feedback! I've made the change in README. It's possible to squash and merge in Github UI, but it is available only for owner and contributors of repository (people with access to approve pull requests). Check if this repository enables squash commits.

Anyway, if this buttons not appears for you, I can squash here in my local machine and send again to this pull request. :thumbsup:

select-squash-and-merge-from-drop-down-menu

**Comment by djoos** [comment]
Perfect, thanks for your contribution @pedrofurtado!

Kind regards,
David

**Comment by pedrofurtado** [comment]
@djoos  Thanks man! If you could release a new version ASAP, I will update the version of bundle here!

**Comment by djoos** [comment]
Sure: [v2.3.0](2.3.0) has been tagged!

**Comment by pedrofurtado** [comment]
@djoos Thanks again!

**Pull request merged**
